import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { useAuth } from './AuthContext'
import { AppShell } from './AccountApp'
import * as api from './lib/supabase'
import './AskWorkspace.css'

function useOrganization() {
  const { user, session } = useAuth()
  const [memberships, setMemberships] = useState([])
  const [organizationId, setOrganizationId] = useState(localStorage.getItem('bullyx.activeOrganization') || '')
  useEffect(() => { api.getMemberships(session.access_token, user.id).then((rows) => { setMemberships(rows); const valid = rows.some((item) => item.organization.id === organizationId); if (!valid && rows[0]) { setOrganizationId(rows[0].organization.id); localStorage.setItem('bullyx.activeOrganization', rows[0].organization.id) } }).catch(() => setMemberships([])) }, [organizationId, session.access_token, user.id])
  function select(id) { setOrganizationId(id); localStorage.setItem('bullyx.activeOrganization', id) }
  return { memberships, organizationId, setOrganizationId: select, organization: memberships.find((item) => item.organization.id === organizationId)?.organization }
}

function OrganizationPicker({ memberships, value, onChange }) {
  return <select className="brain-org-picker" value={value} onChange={(event) => onChange(event.target.value)} aria-label="Active organization"><option value="">Choose organization</option>{memberships.map((item) => <option key={item.id} value={item.organization.id}>{item.organization.name}</option>)}</select>
}

function EmptyOrganization() {
  return <div className="brain-no-org"><span>ORGANIZATION REQUIRED</span><h2>Connect Ask to your company.</h2><p>Create or join an organization first. Each organization has an isolated knowledge base, conversation history, and team of agents.</p><a href="/organizations">Manage organizations →</a></div>
}

function AnswerText({ text }) {
  return <div className="answer-text">{String(text || '').split('\n').map((line, index) => line ? <p key={index}>{line.replace(/^#{1,4}\s*/, '').replace(/^[-*]\s*/, '• ')}</p> : <br key={index} />)}</div>
}

function EvidencePanel({ evidence, selected, onClose }) {
  const document = selected || evidence[0]
  return <aside className={`evidence-panel ${document ? 'has-document' : ''}`}><header><div><p>EVIDENCE</p><h3>{document ? 'Source viewer' : 'Sources will appear here'}</h3></div>{document && <button onClick={onClose} aria-label="Close document">×</button>}</header>{document ? <article><div className="document-meta"><span>{document.kind || 'document'}</span><small>{document.source_label || 'Company knowledge'}</small></div><h2>{document.title}</h2><p className="document-excerpt">{document.content || document.excerpt}</p>{document.external_url && <a href={document.external_url} target="_blank" rel="noreferrer">Open original ↗</a>}</article> : <div className="evidence-empty"><span>⌕</span><p>Ask a question and Bullyx will surface the documents used to support its answer.</p></div>}</aside>
}

function AssignPanel({ open, onClose, organizationId, answer, citations }) {
  const { user, session } = useAuth(); const [title, setTitle] = useState(''); const [agentName, setAgentName] = useState('Operations agent'); const [success, setSuccess] = useState(false); const [error, setError] = useState('')
  useEffect(() => { if (open) { setTitle(answer?.split('\n')[0]?.slice(0, 90) || 'Follow up on Ask response'); setSuccess(false); setError('') } }, [open, answer])
  if (!open) return null
  async function submit(event) { event.preventDefault(); try { await api.createAgentAssignment(session.access_token, { organization_id: organizationId, created_by: user.id, title, agent_name: agentName, instructions: answer, evidence: citations }); setSuccess(true) } catch (err) { setError(err.message) } }
  return <div className="assign-backdrop" onClick={onClose}><section className="assign-panel" onClick={(event) => event.stopPropagation()}><button className="assign-close" onClick={onClose}>×</button><p className="acct-eyebrow">ASSIGN WORK</p><h2>Turn this answer into bounded work.</h2>{success ? <div className="assign-success"><b>Assignment created</b><p>The agent received the company-specific instructions and linked evidence.</p><button onClick={onClose}>Done</button></div> : <form onSubmit={submit}><label>Assignment title<input value={title} onChange={(e) => setTitle(e.target.value)} required /></label><label>Agent<select value={agentName} onChange={(e) => setAgentName(e.target.value)}><option>Incident evidence agent</option><option>Field-service coordinator</option><option>Engineering research agent</option><option>Customer-program agent</option></select></label><label>Instructions<textarea value={answer} readOnly rows="8" /></label><p>{citations.length} evidence source{citations.length === 1 ? '' : 's'} will be attached. Agent output remains unverified.</p>{error && <p className="acct-error">{error}</p>}<button className="brain-primary">Create assignment →</button></form>}</section></div>
}

export default function AskWorkspace() {
  const { session, profile } = useAuth(); const { memberships, organizationId, setOrganizationId, organization } = useOrganization()
  const [threads, setThreads] = useState([]); const [conversationId, setConversationId] = useState(''); const [messages, setMessages] = useState([]); const [question, setQuestion] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [selectedEvidence, setSelectedEvidence] = useState(null); const [assigning, setAssigning] = useState(false)
  const textarea = useRef(null); const lastAnswer = [...messages].reverse().find((item) => item.role === 'assistant')
  const evidence = useMemo(() => lastAnswer?.citations || [], [lastAnswer])

  const loadThreads = useCallback(async () => { if (!organizationId) { setThreads([]); return } try { setThreads(await api.getConversations(session.access_token, organizationId)) } catch { setThreads([]) } }, [organizationId, session.access_token])
  useEffect(() => { loadThreads(); setConversationId(''); setMessages([]) }, [loadThreads])
  async function openThread(id) { setConversationId(id); setSelectedEvidence(null); setMessages(await api.getConversationMessages(session.access_token, id)) }
  function newThread() { setConversationId(''); setMessages([]); setQuestion(''); setSelectedEvidence(null); textarea.current?.focus() }
  async function submit(event, suggestedQuestion) {
    event?.preventDefault(); const prompt = (suggestedQuestion || question).trim(); if (!prompt || !organizationId || busy) return
    const optimistic = { id: `temp-${Date.now()}`, role: 'user', content: prompt, citations: [] }; setMessages((items) => [...items, optimistic]); setQuestion(''); setBusy(true); setError(''); setSelectedEvidence(null)
    try { const result = await api.askCompanyBrain(session.access_token, { organizationId, conversationId: conversationId || null, question: prompt }); setConversationId(result.conversationId); setMessages((items) => [...items.filter((item) => item.id !== optimistic.id), result.userMessage, result.assistantMessage]); await loadThreads() } catch (err) { setMessages((items) => items.filter((item) => item.id !== optimistic.id)); setQuestion(prompt); setError(err.message.includes('Failed to fetch') ? 'Ask is not deployed yet. Finish the Qwen server connection to activate answers.' : err.message) } finally { setBusy(false) }
  }
  async function feedback(messageId, rating) { try { await api.saveAnswerFeedback(session.access_token, { message_id: messageId, rating, created_by: profile.id }); setMessages((items) => items.map((item) => item.id === messageId ? { ...item, feedback: rating } : item)) } catch (err) { setError(err.message) } }

  return <AppShell title="Ask" eyebrow="COMPANY BRAIN" flush><div className="brain-shell"><aside className="thread-panel"><button className="new-thread" onClick={newThread}>＋ New question</button><p>RECENT</p><div>{threads.map((thread) => <button key={thread.id} className={thread.id === conversationId ? 'active' : ''} onClick={() => openThread(thread.id)}><span>{thread.title}</span><small>{new Date(thread.updated_at).toLocaleDateString()}</small></button>)}</div><div className="thread-org"><span>WORKSPACE</span><OrganizationPicker memberships={memberships} value={organizationId} onChange={setOrganizationId} /></div></aside>
    <section className="chat-panel">{!organizationId ? <EmptyOrganization /> : messages.length ? <div className="message-stream">{messages.map((message) => <article key={message.id} className={`chat-message ${message.role}`}><div className="message-author">{message.role === 'user' ? 'YOU' : 'BULLYX ASK'}{message.role === 'assistant' && <span><i /> Grounded in {message.citations?.length || 0} sources</span>}</div><AnswerText text={message.content} />{message.role === 'assistant' && <footer><div>{(message.citations || []).map((citation, index) => <button key={citation.id || index} onClick={() => setSelectedEvidence(citation)}><span>{index + 1}</span>{citation.title}</button>)}</div><section><button className={message.feedback === 1 ? 'selected' : ''} onClick={() => feedback(message.id, 1)} aria-label="Helpful answer">↑</button><button className={message.feedback === -1 ? 'selected' : ''} onClick={() => feedback(message.id, -1)} aria-label="Unhelpful answer">↓</button><button onClick={() => { setAssigning(true) }}>Assign to agent ↗</button></section></footer>}</article>)}{busy && <article className="chat-message assistant thinking"><div className="message-author">BULLYX ASK <span><i /> Searching {organization?.name}</span></div><div><b/><b/><b/></div></article>}</div> : <div className="ask-empty"><div className="brain-orb">B</div><p className="acct-eyebrow">ASK ACROSS {organization?.name?.toUpperCase()}</p><h2>What do you need to know?</h2><p>Ask about incidents, robots, deployments, customer programs, policies, or how your team handled a similar situation. Answers stay linked to their evidence.</p><div className="suggestion-grid">{['What happened during INC-204?','Why is RBT-017 still quarantined?','What evidence supports return to service?','What is blocking the DashDrop pilot?'].map((item) => <button key={item} onClick={() => submit(null, item)}>{item}<span>↗</span></button>)}</div></div>}
      {organizationId && <form className="ask-composer" onSubmit={submit}><textarea ref={textarea} value={question} onChange={(e) => setQuestion(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); submit(e) } }} placeholder={`Ask ${organization?.name || 'your company'} anything…`} rows="1" /><div><span>Searches only the data you can access</span><button disabled={!question.trim() || busy} aria-label="Send question">↑</button></div>{error && <p role="alert">{error}</p>}</form>}</section><EvidencePanel evidence={evidence} selected={selectedEvidence} onClose={() => setSelectedEvidence(null)} /></div><AssignPanel open={assigning} onClose={() => setAssigning(false)} organizationId={organizationId} answer={lastAnswer?.content || ''} citations={evidence} /></AppShell>
}

export function KnowledgeWorkspace() {
  const { session, user } = useAuth(); const { memberships, organizationId, setOrganizationId, organization } = useOrganization(); const [documents, setDocuments] = useState([]); const [showAdd, setShowAdd] = useState(false); const [title, setTitle] = useState(''); const [content, setContent] = useState(''); const [error, setError] = useState('')
  const load = useCallback(() => organizationId && api.getKnowledgeDocuments(session.access_token, organizationId).then(setDocuments).catch((err) => setError(err.message)), [organizationId, session.access_token]); useEffect(() => { load() }, [load])
  async function add(event) { event.preventDefault(); try { await api.createManualDocument(session.access_token, { organization_id: organizationId, created_by: user.id, title, content, kind: 'note', source_label: 'Manual knowledge' }); setTitle(''); setContent(''); setShowAdd(false); load() } catch (err) { setError(err.message) } }
  const connectors = [['Fleet systems','Robot and deployment events'],['GitHub','Engineering activity'],['Maintenance','Work orders and serialized parts'],['Telemetry','MCAP, ROS bag, and recording manifests'],['Slack','Operational discussions'],['Google Drive','Policies and documents']]
  return <AppShell title="Knowledge" eyebrow="CONTINUOUS INDEX"><div className="workspace-title"><div><h2>Your company’s living memory.</h2><p>New information is normalized and indexed incrementally—no model retraining or downtime required.</p></div><OrganizationPicker memberships={memberships} value={organizationId} onChange={setOrganizationId} /></div>{!organizationId ? <EmptyOrganization /> : <><section className="knowledge-stats"><article><span>INDEXED DOCUMENTS</span><b>{documents.length}</b><small>Available to Ask</small></article><article><span>CONNECTED SOURCES</span><b>0</b><small>Ready for setup</small></article><article><span>LAST INDEXED</span><b>{documents[0] ? new Date(documents[0].indexed_at).toLocaleDateString() : '—'}</b><small>{organization?.name}</small></article></section><section className="knowledge-section"><header><div><p className="acct-eyebrow">DATA SOURCES</p><h3>Connect company systems</h3></div><span>Connector credentials required</span></header><div className="connector-cards">{connectors.map(([name, description]) => <article key={name}><div>{name[0]}</div><section><b>{name}</b><small>{description}</small></section><button title={`${name} setup coming next`}>＋</button></article>)}</div></section><section className="knowledge-section"><header><div><p className="acct-eyebrow">KNOWLEDGE LIBRARY</p><h3>Indexed records</h3></div><button className="brain-secondary" onClick={() => setShowAdd(!showAdd)}>＋ Add knowledge</button></header>{showAdd && <form className="manual-document" onSubmit={add}><input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Document title" required /><textarea value={content} onChange={(e) => setContent(e.target.value)} placeholder="Paste a policy, process, customer note, or other company knowledge…" rows="7" required /><button className="brain-primary">Index document →</button></form>}{error && <p className="acct-error">{error}</p>}{documents.length ? <div className="document-table">{documents.map((doc) => <article key={doc.id}><span>{doc.kind?.slice(0,1).toUpperCase()}</span><div><b>{doc.title}</b><small>{doc.source_label} · indexed {new Date(doc.indexed_at).toLocaleDateString()}</small></div><em>Ready</em></article>)}</div> : <div className="knowledge-empty"><b>No knowledge indexed yet</b><p>Add a document now or connect the first company system.</p></div>}</section></>}</AppShell>
}

export function AgentsWorkspace() {
  const { session } = useAuth(); const { memberships, organizationId, setOrganizationId } = useOrganization(); const [assignments, setAssignments] = useState([]); const [error, setError] = useState('')
  useEffect(() => { if (organizationId) api.getAgentAssignments(session.access_token, organizationId).then(setAssignments).catch((err) => setError(err.message)) }, [organizationId, session.access_token])
  return <AppShell title="Agents" eyebrow="GOVERNED EXECUTION"><div className="workspace-title"><div><h2>Work with company context.</h2><p>Assignments carry specific instructions, supporting evidence, and a clear human owner.</p></div><OrganizationPicker memberships={memberships} value={organizationId} onChange={setOrganizationId} /></div>{!organizationId ? <EmptyOrganization /> : <section className="knowledge-section agent-section"><header><div><p className="acct-eyebrow">ASSIGNMENT QUEUE</p><h3>Agent work</h3></div><span>{assignments.length} total</span></header>{error && <p className="acct-error">{error}</p>}{assignments.length ? <div className="assignment-list">{assignments.map((item) => <article key={item.id}><div className="agent-icon">A</div><div><b>{item.title}</b><small>{item.agent_name} · {new Date(item.created_at).toLocaleString()}</small></div><span className={`assignment-status ${item.status}`}>{item.status}</span><p>{item.instructions}</p></article>)}</div> : <div className="knowledge-empty"><b>No work assigned yet</b><p>Ask a company question, then turn the grounded answer into an agent assignment.</p><a href="/dashboard">Go to Ask →</a></div>}</section>}</AppShell>
}
